### PR TITLE
SCANNERAPI-189 Fix connection leaks

### PR DESCRIPTION
**Pull request by damien-urruty-sonarsource**

### CODE REVIEW

**Review by dbmeneses — APPROVED** [review]
LGTM!

**Comment by dbmeneses** [comment]
Perhaps "Connection leaks" would be a better title for the ticket?
I don't think memory leak is the main concern and it sounds way more alarming that what it is.

**Comment by damien-urruty-sonarsource** [comment]
Yep you're right @dbmeneses, Will change it. By the way do you know why the checks has failed ? Not sure it's related to my changes

**Comment by dbmeneses** [comment]
> Yep you're right @dbmeneses, Will change it. By the way do you know why the checks have failed ? Not sure it's related to my changes

I reproduced in my machine and I think it's just a test library that is out of date. I submitted a separate PR to fix that.

**Pull request merged**
