### PR TITLE
SUPPORT-10616 Change timeouts to be configurable

### PR DESCRIPTION
**Pull request by CSchulz**

### CODE REVIEW

**Comment by henryju** [comment]
@CSchulz I'm closing this PR since it is now outdated. If you still face an issue with the default timeout, let me know and I will create a ticket.

**Comment by CSchulz** [comment]
Why is this PR outdated? The sources didn't changed.

**Comment by henryju** [comment]
I meant it was opened long time ago, with no other reports of people having an issue with timeouts. Do you still need those changes?

**Comment by CSchulz** [comment]
@henryju Yes we still need this change, because with every update of plugins or SonarQube our Jenkins slave also needs to update them. There is a slow anti virus proxy between the Jenkins and SonarQube breaking the update process.
At the moment we are doing this with manual copying the files.

**Comment by henryju** [comment]
This HTTP client is only used to download the scanner engine (so only when SQ is updated). Plugins are downloaded using the http client in the scanner engine, and there is already a way to control the read timeout:
https://github.com/SonarSource/sonarqube/blob/d08c839cb2433f58a35505da8f58e418c23ce1ae/sonar-scanner-engine/src/main/java/org/sonar/scanner/bootstrap/ScannerWsClientProvider.java#L36

So I will open a ticket to extend this parameter to work with the scanner-api. But I think using the same parameter is better: `sonar.ws.timeout` Also I think making only the read timeout configurable is enough.

**Comment by CSchulz** [comment]
Oh ... that could be possible, we finally copied all files manually.

I can edit this PR to match the parameter name and clean it up.

**Comment by henryju** [comment]
In fact I just came across the (partial) fix that was done for SUPPORT-10616. The solution was simply to hardcode a read timeout of 5min when downloading plugin JARs. To be consistent, we should do the same in the scanner-api to download the scanner-engine:
https://jira.sonarsource.com/browse/SCANNERAPI-182

**Comment by henryju** [comment]
So if you want you can simply reopen a new PR with an update of the default value. Or we will do it during next sprint.

**Comment by CSchulz** [comment]
Alright, I will do it next week at least.

**Comment by CSchulz** [comment]
@henryju I have created a new PR #60

**Pull request closed without merging**
